- name: playbook for creating the e2_instance in aws
  hosts: localhost
  become: true
  connection: local
  gather_facts: true
  tasks:
    - name: importing the variables
      include_vars: variables/Bastion_setup

    - name: importing the variables
      include_vars: variables/output_vars

    - name: creating the key pair in aws
      ec2_key:
        Name: vprofile-key
        region: "{{region}}"
      register: key_out

    - name: creating the
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed = true






