- name: creating the bastion instance in aws
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: importing the variables
      include_vars: variables/Bastion_setup

    - name: importing ghe variables
      include_vars: variables/output_vars

    - name: creating the key pair in aws
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    - name: save the private key file
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
        when: key_out.changed = true

    - name: creating the security group for bastion hosts
      ec2_group:
        name: Bastion-host-sg
        description:
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: Bastionsg_out

    - name: creating the instance for bastion host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          name: "Bastion_host"
          project: vprofile
          owner: Devops
        exact_count: 1
        count_tag:
          name: "Bastion_host"
          project: vprofile
          owner: Devops
        group_id: "{{Bastionsg_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionhost_out
