- name: playbook for vcp setup in aws
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - Name: importing the variables
      include_vars: variables/vpc_setup

    - Name: creating the vpc setup
      ec2_vpc_net:
        name: "{{vpc_name}}"
        region: "{{region}}"
        cidr_block: "{{vpccidr}}"
        tenancy: default
        dns_support: true
        dns_hostnames: true
        state: present
      register: vpcout

    - debug:
        var: vpcout

    - name: creating the public subnet1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{pubsub1cidr}}"
        state: present
        map_public: yes
        tags:
          Name: vprofile-pubsubnet1
      register: pubsub1_out

     - name: creating the public subnet2
       ec2_vpc_subnet:
         vpc_id: "{{vpcout.vpc.id}}"
         region: "{{region}}"
         az: "{{zone2}}"
         cidr: "{{pubsub2cidr}}"
         state: present
         map_public: yes
         tags:
           Name: vprofile-pubsubnet2
       register: pubsub2_out

    - name: creating the public subnet3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        cidr: "{{pubsub3cidr}}"
        state: present
        map_public: yes
        tags:
          Name: vprofile-pubsubnet3
      register: pubsub3_out

    - name: creating the private subnet1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{prisub2cidr}}"
        state: present
        tags:
          Name: vprofile-prisubnet1
      register: prisub1_out

    - name: creating the private subnet2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{prisub2}}"
        state: present
        tags:
          Name: vprofile-prisubnet2
      register: prisub2_out

    - name: creating the private subnet3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        cidr: "{{prisub3}}"
        state: present
        tags:
          Name: vprofile-prisubnet3
      register: prisubnet3_out

    - name: Internet Gateway Setup
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        tags:
          Name: vprofile-IGW
      register: vpcigw_out

    - name: creating the public route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        subnets:
          - "{{pubsub1_out.subnet.id}}"
          -  "{{pubsub2_out.subnet.id}}"
          -  "{{pubsub3_out.subnet.id}}"
        routes:
          dest: 0.0.0.0/0
          gateway_id: "{{vpcigw_out.gateway_id}}"
        tags:
          Name: vprofile_public_route
      register: pubRT_out

    - name: creating the nat gateway
      ec2_vpc_nat_gateway:
        state: present
        subnet_id: "{{pubsub1_out.subnet.id}}"
        region: "{{region}}"
        wait: true
        if_exist_do_not_create: true
      register: natgw_out

    - name: creating the route table in private subnets
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        state: present
        region: "{{region}}"
        tags:
          Name: vprofile-PriRT
        subnets:
          - "{{prisub1cidr.subnet.id}}"
          - "{{prisub2cidr.subnet.id}}"
          - "{{prisub3cidr.subnet.id}}"
        routes:
          dest: 0.0.0.0/0
          gateway_id: "{{natgw_out.nat.nat_gateway_id}}"
      register: priRT_out

    - debug:
        - var: "{{item}}"
      loop:
        - vpcout_vpc_id
        - pubsub1_out.subnet.id
        - pubsub2_out.subnet.id
        - pubsub3_out.subnet.id
        - prisub1_out.subnet.id
        - prisub2_out.subnet.id
        - prisub3_out.subnet.id
        - igw_out.gateway.id
        - pubRT_out.route_table.id
        - natgw_out.nat_gateway_id
        - priRT_out.route_table.id
    - set_fact:
        vpcid: "{{pubsub1_out.subnet.id}}"
        pubsub1id: "{{pubsub1_out.subnet.id}}"
        pubsub2id: "{{pubsub2_out.subnet.id}}"
        pubsub3id: "{{pubsub3_out.subnet.id}}"
        prisub1id: "{{prisub1_out.subnet.id}}"
        prisub2id: "{{pirsub2_out.subnet.id}}"
        prisub3id: "{{prisub3_out.subnet.id}}"
        igwid: "{{igw_out.gateway_id}}"
        pubRTid: "{{pubRT_out.route_table.id}}"
        natigwid: "{{natgw_out.nat_table.id}}"
        priRTid: "{{pirRT_out.route_table.id}}"
        cacheable: yes







