- name: playbook for ec2 stacks
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: importing the variables
      include_vars: variables/output_vars

    - name: importing the variables
      include_vars: variables/vprofile-stack

    - name: creating the key pair in aws
      ec2_key:
        name: vprofile-loginkey
        region: "{{region}}"
        state: present
      register: key_out

    - debug:
        var: key_out

    - name:
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./loginkey.pem"
        mode: 0600
      when: key_out.changed

